#!/usr/bin/env ruby

require "jrubyfx"

class HelloWorld < JRubyFX::Application
  def start(stage)
    with(stage, width: 300, height: 300, title: "Hello, World!") do
      layout_scene do
        label("Hello, World!")
      end
      show
    end
  end
end

HelloWorld.launch
