#!/usr/bin/env python3

import webview

html="""
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
      body {
        margin: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background-color: #444;
        color: #fff;
        min-height: 100vh;
      }
    </style>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
"""

window = webview.create_window(
  "Hello, World!",
  html=html
)
webview.start()
